server:
  port: 8094

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/sbt_board?serverTimezone=Asia/Seoul
    username: root
    password: 12345

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper_xml/**/*.xml

logging:
  level:
    jdbc:
      audit: warn
      connection: warn
      resultset: warn
      resultsettable: info
      sqlonly: warn
      sqltiming: info